image: python:3.10

stages:
  - test

test_job:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "🚀 Starting Tests..."
    - pytest
    - echo "✅ Tests Passed!"
